apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9vbmthcmRldmFsZTo0R3J0WmNBWmNQT2ZlRHVHQGNsdXN0ZXIwLm1hY2VkYm8ubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
  MONGODB_DATABASE: b3JkZXJz